name: Fnx
channels:
  - conda-forge
dependencies:
  - libblas * *mkl
  - scipy
  - numpy
  - sympy
  - ipywidgets
  - ipympl
  - matplotlib
  - jupyterlab
  - altair
  - pandas
  - pip
  - python=3.9
  - tabulate
  - pip:
     - baryrat
